// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIB-enEVXeZK9CNw_jJCjMjvcOR_k_iYM',
    appId: '1:310637651324:web:5e2441ada088fc6077f0f9',
    messagingSenderId: '310637651324',
    projectId: 'proteus-firebase-iot',
    authDomain: 'proteus-firebase-iot.firebaseapp.com',
    databaseURL: 'https://proteus-firebase-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proteus-firebase-iot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAm5iBEWaI0cfDxt7ZYE043gN7I79gWOQ',
    appId: '1:310637651324:android:dc0266b3c3503b0477f0f9',
    messagingSenderId: '310637651324',
    projectId: 'proteus-firebase-iot',
    databaseURL: 'https://proteus-firebase-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proteus-firebase-iot.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIB-enEVXeZK9CNw_jJCjMjvcOR_k_iYM',
    appId: '1:310637651324:web:227e0bcfb5d10da677f0f9',
    messagingSenderId: '310637651324',
    projectId: 'proteus-firebase-iot',
    authDomain: 'proteus-firebase-iot.firebaseapp.com',
    databaseURL: 'https://proteus-firebase-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proteus-firebase-iot.appspot.com',
  );
}
